### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by PatParslow** [ob6160/Terrain#7]
Is it worth writing down a roadmap, identifying specific features with a rough timeline to help focus your efforts?
E.G. build a basic fractal terrain generator first that can be rendered in existing engines.  Implement a simple erosion model.  Get something you can demo, and then develop/build on the specific techniques (maybe implementing more than one so you can compare and contrast)?

**Comment by ob6160** [comment]
Agreed, good idea to get some realistic goals down with a timescale.
I'll put something together soon
